### ISSUE TITLE
Listing endpoint improvement

### ISSUE THREAD

**Issue by deven96** [Go-phie/ocena#6]
We can make sure the listing returns endpoints by most recent according to how it was posted on the app
We add a `saved_on` column to Movie. Then since ocena is the one calling gophie, we can take the page number(when it is list)
We can now use it to set a datetime object on the returned object, e.g if the page number is 1, we set `saved_on` to be a day behind... if it is page 2, we set `saved_on` to be 2 days behind. This way, when we order by `saved on`, recent movies will tend to cluster at the top and our listing wouldn't look like random selections...

**Comment by MeNsaaH** [comment]
Is the method efficient

**Comment by deven96** [comment]
Yeah ... think about it
